services:
  dkv:
    image: ghcr.io/valentinkolb/dkv:latest
    container_name: dkv-server
    restart: unless-stopped
    ports:
      # The RPC server starts automatically on port 8080, to change this set the DKV_ENDPOINT environment variable
      - "8080:8080"
      # - "63001:63001" # Uncomment if you want to expose the Raft port
    environment:

      # Go runtime configuration
      GOGC: 100 # A lower value will use more memory, a higher value will use less but will be slower
      GOMEMLIMIT: "2GiB"
      GOMAXPROCS: 4 # Should be set to the number of CPU cores available

      # DVK specific configuration
      # General
      DKV_LOG_LEVEL: "info"
      DKV_TIMEOUT: 15 # Timeout in seconds, used for various operations
      # RAFT
      DKV_RTT_MILLISECOND: 100
      DKV_SNAPSHOT_ENTRIES: 5000
      DKV_COMPACTION_OVERHEAD: 2500
      # Cluster
      DKV_REPLICA_ID: "node-1" # Unique identifier for this node
      DKV_CLUSTER_MEMBERS: "node-1=localhost:63001,node-2=localhost:63002,node-3=localhost:63003" # All nodes must be on the same network
      # RPC Server
      DKV_TRANSPORT: "tcp"
      DKV_SERIALIZER: "binary"
      DKV_WORKERS: 10 # Number of workers per connection, higher values may improve performance but increase memory usage
      DKV_BUFFER_POOL_SIZE: 64 # Size of pre-allocated buffers in MB, should reflect the message size

      # DKV_ENDPOINT: ":8080" # Change address of the RPC server

    volumes:
      # Mount for persistent data storage
      - dkv-data:/app/data
    networks:
      - dkv-network
    deploy:
      resources: # Adjust resource limits and reservations as needed
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 2G

networks:
  dkv-network:
    driver: bridge

volumes:
  dkv-data:
    driver: local