# Release Workflow with GoReleaser
#
# This workflow creates binary releases for the dkv CLI tool using GoReleaser.
# It builds cross-platform binaries for Linux and macOS (both AMD64 and ARM64).
#
# The workflow is triggered only when pushing version tags (v*).
# Binaries are automatically uploaded to GitHub Releases page with checksums.

name: Release Binaries

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.23.0'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}